### ISSUE TITLE
Can HMR work when compiling to multiple files?

### ISSUE THREAD

**Issue by jacksonrayhamilton** [brunch/hmr-brunch#1]
In the README, it says that this package "Works only if your JS compiles to a single file." Is there a technical reason this isn't possible, or is that capability just not implemented yet?

I think it might be useful, since it could keep my configuration simpler: I wouldn't need a different `joinTo` configuration for development and production.

**Comment by goshacmd** [comment]
To give a little insight on how HMR works — in dev mode, it wraps all of the modules into a `require.hmr(function() { /* modules */ })` call. What it basically does is figure out the new modules being registered, and tries to diff from the currently loaded modules, and apply that diff.

So it won't work with multiple files, as these will require a different, and probably more complex, way to signal when updated JS is a) being received (as to prepare to diff), b) finished loading (as to diff & apply).

**Comment by jacksonrayhamilton** [comment]
Okay, thanks for the explanation.

**Comment by phillipp** [comment]
I'm sorry but I don't understand the reason. Is it impossible or just not very easy?

Wouldn't a naive solution that just hot-replaces every module be possible? I have such a solution in place (websocket, server and client compüare timestamps of latest assets file), but I'm looking into a solution that loads less modules on easy reload (just because, not because I think I need it at this time)...

Additionally, the solution I'm using just appends a new stylesheet at the end after each reload. This doesn't remove existing styles but only overwrite existing ones, bus it catches 80-90% of all CSS changes and for me that's enough for a productivity boost.
